### 1-1 : Affine Functions with 1 Feature

####Code.1-1-1: Affine Function

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]])  #  input setting(Note: input -> matrix)
print(x)
dense = Dense(units=1, activation='linear')    # imp. an affine function

y_tf = dense(x)  # forward propagation + params initialization
print(y_tf)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B  # forward propagation(manual)

# print results
print('===== Input/Weight/Bias =====')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("b: {}\n{}\n".format(B.shape, B))

print('===== Outputs =====')
print("y(tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[2.5108492]], shape=(1, 1), dtype=float32)
===== Input/Weight/Bias =====
x: (1, 1)
[[10.]]

W: (1, 1)
[[0.25108492]]

b: (1,)
[0.]

===== Outputs =====
y(tensorflow): (1, 1)
[[2.5108492]]

y(Manual): (1, 1)
[[2.5108492]]



####Code.1-1-2: Params Initialization

In [9]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.constant([[10.]])

# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

# imp. an affine function
dense = Dense(units=1,
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

y_tf = dense(x)
print(y_tf)

W, B = dense.get_weights()

# print results
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]

B: (1,)
[20.]



###1-2: Affine Functions with n features

####Code.1-2-1: Affine functions with n features

In [10]:
import tensorflow as tf 
from tensorflow.keras.layers import Dense 

x = tf.random.uniform(shape=(1, 10), minval=0, maxval=10)

dense = Dense(units=1)

y_tf = dense(x)

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

# print results
print('===== Input/Weight/Bias =====')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("b: {}\n{}\n".format(B.shape, B))

print('===== Outputs =====')
print("y(tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

===== Input/Weight/Bias =====
x: (1, 10)
[[3.665719   0.35254002 1.4175129  4.7933197  5.914835   8.116751
  1.5063477  6.386818   1.4767075  7.737359  ]]

W: (10, 1)
[[ 0.7339563 ]
 [-0.15992653]
 [ 0.7256499 ]
 [ 0.6267063 ]
 [-0.29436016]
 [-0.06378531]
 [ 0.4560457 ]
 [ 0.16595948]
 [ 0.11167425]
 [-0.3856184 ]]

b: (1,)
[0.]

===== Outputs =====
y(tensorflow): (1, 1)
[[3.3360567]]

y(Manual): (1, 1)
[[3.3360567]]

