In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

In [6]:
N, n_H, n_W, n_C = 8, 28, 28, 5
n_filter = 10
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))
conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
print(y.shape)

(8, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(8, 26, 26, 10)


####Code.5-1-2: Correlation Calculation

In [10]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))
conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)
# print("Y(Tensorflow): ", y.numpy())
print("Y(Tensorflow): ", y.numpy().squeeze())

W, B = conv.get_weights()
####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        window = images[i:i+k_size, j:j+k_size]
        y_man[i][j] = np.sum(window * W) + B

print("Y(Manual): \n", y_man)

Y(Tensorflow):  [[ 0.21225736  0.16771875  0.49865505]
 [ 0.11339864  0.16210717  0.17285945]
 [-0.23546562  0.04724701  0.41748965]]
Y(Manual): 
 [[ 0.21225736  0.16771875  0.49865502]
 [ 0.11339864  0.16210717  0.17285946]
 [-0.23546568  0.04724699  0.41748965]]


####Code.5-1-3: Correlation with n-channel

In [12]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_C)))
conv = Conv2D(filters=n_filter, kernel_size=k_size)

y = conv(images)
# print("Y(Tensorflow): ", y.numpy())
print("Y(Tensorflow): ", y.numpy().squeeze())

W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()

# print(images.shape)
# print(W.shape)

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        window = images[i:i+k_size, j:j+k_size, :]
        y_man[i][j] = np.sum(window * W) + B

print("Y(Manual): \n", y_man)

Y(Tensorflow):  [[ 0.17221326  0.02853942 -0.7081085 ]
 [ 0.38368446 -0.60936844 -0.09790278]
 [-0.21355444 -0.06978662  0.2159243 ]]
Y(Manual): 
 [[ 0.17221324  0.02853936 -0.70810854]
 [ 0.38368452 -0.6093685  -0.09790275]
 [-0.21355432 -0.06978665  0.21592423]]
