###5-2: Conv2D Layer with Filters

####Code.5-2-1: Shapes with Filters

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

In [4]:
N, n_H, n_W, n_C = 16, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))
conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Images: {}".format(images.shape))
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))



Input Images: (16, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (16, 26, 26, 5)


####Code.5-2-2: Computations with Filters

In [17]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D 

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4
images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)

# print(Y.numpy().squeeze().shape)
# print(np.transpose(Y.numpy().squeeze(), (2, 0, 1)))  # 익숙한 형태로 차원 변경

Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(Tensorflow): \n", Y)
print('\n')

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for filter_idx in range(n_filter):  # output image의 갯수(n_filter)만큼, 반복문 수행
    sub_W = W[:, :, :, filter_idx]  # filter_idx 번째의 Weight tensor를 선택
    # filter_idx 번째 image tensor 계산
    for i in range(n_H - k_size + 1):  
        for j in range(n_W - k_size + 1):
            Y_man[i][j][filter_idx] = np.sum(sub_W*images[i:i+k_size, j:j+k_size, :]) + B[filter_idx]

print("Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[ 0.89923     0.32374558]
  [ 1.0252571   0.9789649 ]]

 [[ 0.47140798  0.5786967 ]
  [ 0.2220582   0.07091095]]

 [[-0.6543     -0.45121536]
  [-0.6096196  -1.0519056 ]]]


Y(Manual): 
 [[[ 0.89922988  0.32374561]
  [ 1.02525711  0.97896498]]

 [[ 0.47140801  0.57869679]
  [ 0.22205821  0.07091096]]

 [[-0.65429991 -0.45121539]
  [-0.60961974 -1.05190563]]]


In [11]:
import numpy as np 

images = np.random.randint(low=0, high=10, size=(2, 3, 4))
# print(images)
for channel_idx in range(4):
    print(images[:, :, channel_idx])
print('\n')

# 차원 변경
images = np.transpose(images, (2, 0, 1))
# print(images)
for channel_idx in range(4):
    print(images[channel_idx, :, :])

[[1 0 7]
 [4 3 6]]
[[1 1 0]
 [7 2 2]]
[[9 1 1]
 [0 4 2]]
[[3 9 7]
 [3 4 9]]


[[1 0 7]
 [4 3 6]]
[[1 1 0]
 [7 2 2]]
[[9 1 1]
 [0 4 2]]
[[3 9 7]
 [3 4 9]]


###5-3: Conv2D Layers with Activation Functions

####Code.5-3-1: Conv2D Layers with Activation Fuctions

In [19]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D 

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4
images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)


Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(Tensorflow): \n", Y)
print('\n')

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for filter_idx in range(n_filter):  # output image의 갯수(n_filter)만큼, 반복문 수행
    sub_W = W[:, :, :, filter_idx]  # filter_idx 번째의 Weight tensor를 선택
    # filter_idx 번째 image tensor 계산
    for i in range(n_H - k_size + 1):  
        for j in range(n_W - k_size + 1):
            Y_man[i][j][filter_idx] = np.sum(sub_W*images[i:i+k_size, j:j+k_size, :]) + B[filter_idx]
            Y_man[i][j][filter_idx] = 1 / (1 + np.exp(-Y_man[i][j][filter_idx]))   # sigmoid function

print("Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[0.5053224  0.59092164]
  [0.47656134 0.5303132 ]]

 [[0.4005374  0.51496494]
  [0.483007   0.49487284]]

 [[0.35514277 0.35171834]
  [0.41731748 0.37820995]]]


Y(Manual): 
 [[[0.50532238 0.59092165]
  [0.47656136 0.53031319]]

 [[0.40053739 0.51496494]
  [0.48300702 0.49487284]]

 [[0.35514276 0.35171833]
  [0.41731745 0.37820993]]]
