###6-1: Max/Avg Pooling

####Code.6-1-1: Max Pooling


In [4]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1
x = tf.random.normal(shape=(1, L, 1))
pool_max = MaxPooling1D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, pooled_max.numpy().flatten()))

x = x.numpy().flatten() 
pool_max_man = np.zeros((L-f+1, ))
for i in range(L-f+1):
    window = x[i:i+f]
    pool_max_man[i] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pool_max_man.shape, pool_max_man))

x: (1, 10, 1)
[ 0.7564282   1.2570354   0.6932088  -0.04873174 -0.01743953 -0.5688602
 -0.47788042 -0.0139857  -0.12698546 -0.93129647]
pooled_max(Tensorflow): (1, 9, 1)
[ 1.2570354   1.2570354   0.6932088  -0.01743953 -0.01743953 -0.47788042
 -0.0139857  -0.0139857  -0.12698546]
pooled_max(Manual): (9,)
[ 1.25703537  1.25703537  0.69320881 -0.01743953 -0.01743953 -0.47788042
 -0.0139857  -0.0139857  -0.12698546]


####Code.6-1-2: Average Pooling

In [5]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import AveragePooling1D 

L, f, s = 10, 2, 1

x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size=f, strides=s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L-f+1, ))
for i in range(L-f+1):
    pooled_avg_man[i] = np.mean(x[i:i+f])

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape, pooled_avg_man))

x: (1, 10, 1)
[ 0.92174196  0.5192898  -0.5547683   0.00542022  0.26647878 -1.0826852
 -0.15200739 -0.4415325  -1.0117067   0.99413   ]
pooled_avg(Tensorflow): (1, 9, 1)
[ 0.72051585 -0.01773927 -0.27467406  0.13594949 -0.40810323 -0.6173463
 -0.29676995 -0.7266196  -0.00878835]
pooled_avg(Manual): (9,)
[ 0.72051585 -0.01773927 -0.27467406  0.13594949 -0.40810323 -0.61734629
 -0.29676995 -0.7266196  -0.00878835]


###6-2: 2D Max/Avg Pooling


####Code.6-2-1: 2D Max Pooling

In [8]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import MaxPooling2D 

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1 

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().squeeze()))

print('\n')

x = x.numpy().squeeze() 
pooled_max_man = np.zeros((n_H-f+1, n_W-f+1))
for r_idx in range(n_H-f+1):
    for c_idx in range(n_W-f+1):
        window = x[r_idx:r_idx+f, c_idx:c_idx+f]
        pooled_max_man[r_idx, c_idx] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                              pooled_max_man))

x: (1, 5, 5, 1)
[[-1.7659992  -0.01823786 -0.6174721  -0.9467739  -1.2956139 ]
 [ 0.55297816  1.5467331   0.1341351   0.3456237   0.9683584 ]
 [ 1.0490195  -0.32588497 -0.2139547   1.3313708   0.00988551]
 [-1.2124556   0.9699016  -0.6659627   1.3061897  -1.1628124 ]
 [-0.34536934  1.8591986  -0.09115533  0.4755368   0.52350706]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[1.5467331 1.5467331 0.3456237 0.9683584]
 [1.5467331 1.5467331 1.3313708 1.3313708]
 [1.0490195 0.9699016 1.3313708 1.3313708]
 [1.8591986 1.8591986 1.3061897 1.3061897]]


pooled_max(Manual): (4, 4)
[[1.54673314 1.54673314 0.3456237  0.9683584 ]
 [1.54673314 1.54673314 1.33137083 1.33137083]
 [1.04901946 0.96990162 1.33137083 1.33137083]
 [1.85919857 1.85919857 1.30618966 1.30618966]]


####Code.6-2-2: 2D Average Pooling

In [9]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import AveragePooling2D 

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1 

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size=f, strides=s)
pooled_avg= pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().squeeze()))

print('\n')

x = x.numpy().squeeze() 
pooled_avg_man = np.zeros((n_H-f+1, n_W-f+1))
for r_idx in range(n_H-f+1):
    for c_idx in range(n_W-f+1):
        window = x[r_idx:r_idx+f, c_idx:c_idx+f]
        pooled_avg_man[r_idx, c_idx] = np.mean(window)

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                              pooled_avg_man))

x: (1, 5, 5, 1)
[[-0.30909765 -1.3980407   0.08011512 -0.04937261 -0.04987131]
 [ 0.12362806 -0.31720474  0.518018   -1.5493814   0.22848813]
 [-0.14687927  1.7137161  -1.5434017   0.42502633 -0.03132751]
 [-0.16420463  1.0996403   0.61739     1.1201595   1.3421073 ]
 [ 1.0541868  -0.36517197  2.313867   -0.08480998  1.6532354 ]]
pooled_avg(Tensorflow): (1, 4, 4, 1)
[[-0.47517875 -0.27927807 -0.2501552  -0.3550343 ]
 [ 0.34331506  0.09278193 -0.5374347  -0.23179862]
 [ 0.62556815  0.47183615  0.15479352  0.7139914 ]
 [ 0.4061126   0.91643137  0.9916516   1.007673  ]]


pooled_avg(Manual): (4, 4)
[[-0.47517875 -0.27927807 -0.25015521 -0.35503429]
 [ 0.34331506  0.09278193 -0.5374347  -0.23179862]
 [ 0.62556815  0.47183615  0.15479352  0.7139914 ]
 [ 0.40611261  0.91643137  0.99165159  1.00767303]]
