###6-3: 3D Max/Avg Pooling

####Code.6-3-1: 3D Max Pooling

In [5]:
import math
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.layers import MaxPooling2D 

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s, = 2, 2

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
# print("x: {}\n{}".format(x.shape,
#                          np.transpose(x.numpy().squeeze(), (2, 0, 1))))

pool_max = MaxPooling2D(pool_size=f, strides=s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print("pooled_max(Tensorflow_: {}\n{}".format(pooled_max.shape,
                                              pooled_max_t))

print("\n")

x = x.numpy().squeeze()
n_H_ = math.floor((n_H - f)/s + 1)
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros((n_H_, n_W_, n_C))

for c_idx in range(n_C):
    c_image = x[:, :, c_idx]
    
    h_ = 0
    for h_idx in range(0, n_H-f+1, s):
        w_ = 0
        for w_idx in range(0, n_W-f+1, s):
            window = c_image[h_idx:h_idx+f, w_idx:w_idx+f]
            pooled_max_man[h_, w_, c_idx] = np.max(window)

            w_ += 1
        h_ += 1

pooled_max_man_t = np.transpose(pooled_max_man.squeeze(), (2, 0, 1))
print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_man_t))

pooled_max(Tensorflow_: (1, 2, 2, 3)
[[[0.91352355 1.7952901 ]
  [0.48841143 0.42549095]]

 [[1.5619361  1.3216549 ]
  [0.87588966 1.2939956 ]]

 [[0.9465586  1.0157619 ]
  [0.9499332  1.0154428 ]]]


pooled_max(Manual): (2, 2, 3)
[[[0.91352355 1.79529011]
  [0.48841143 0.42549095]]

 [[1.56193614 1.32165492]
  [0.87588966 1.29399562]]

 [[0.94655859 1.01576185]
  [0.94993317 1.01544285]]]


###6-4: Padding

####Code.6-4-1: ZeroPadding2D Layer

In [6]:
import numpy as np
import tensorflow as tf 
from tensorflow.keras.layers import ZeroPadding2D 

images = tf.random.normal(shape=(1, 3, 3, 3))
# print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

zero_padding = ZeroPadding2D(padding=1)
y = zero_padding(images)

# print(np.transpose(y.numpy().squeeze(), (2, 0, 1))) 

[[[ 0.8224032   0.9040348  -0.29532588]
  [-1.0773661  -0.493752   -1.7083095 ]
  [-0.90497255  0.26019692 -0.56351686]]

 [[ 0.9318055  -0.10138797 -0.37963027]
  [ 0.80178314 -0.16505688  0.84648484]
  [ 0.42477795 -0.376592    0.20618427]]

 [[ 0.86274165  0.3521199  -1.3041879 ]
  [-0.69551075  0.94388586  0.35556948]
  [ 0.6130951   0.4458111  -0.7222598 ]]]
[[[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.8224032   0.9040348  -0.29532588  0.        ]
  [ 0.         -1.0773661  -0.493752   -1.7083095   0.        ]
  [ 0.         -0.90497255  0.26019692 -0.56351686  0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.9318055  -0.10138797 -0.37963027  0.        ]
  [ 0.          0.80178314 -0.16505688  0.84648484  0.        ]
  [ 0.          0.42477795 -0.376592    0.20618427  0.        ]
  [ 0.          0.          0.          0.          0.  

####Code.6-4-2: Zero Padding with Conv2D Layers

In [8]:
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D 

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='same')
y = conv(images)
print(y.shape)

(1, 28, 28, 1)


###6-5: Strides

####Code.6-5-1: Strides in Conv2D Layers

In [11]:
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D 

images = tf.random.normal(shape=(1, 28, 28, 3))
conv = Conv2D(filters=1, kernel_size=3, padding='valid', strides=2)
y = conv(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 1)


####Code.6-5-2: Strides in Pooling Layers

In [14]:
import tensorflow as tf 
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape=(1, 28, 28, 3))
pool = MaxPooling2D(pool_size=3, strides=2)
y = pool(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
