###1-3. Activation Functions

####Code.1-3-1: Activation Layers

In [3]:
import tensorflow as tf
from tensorflow.math import exp, maximum 
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1, 5))  # input setting

# imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(Manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(Manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLU(Manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x: (1, 5)
[[-1.7044843  -0.21769346  0.45682108  0.3009945  -1.3526518 ]]
Sigmoid(Tensorflow): (1, 5)
[[0.15388048 0.44579056 0.61225975 0.5746856  0.20543715]]
Sigmoid(Manual): (1, 5)
[[0.15388049 0.44579053 0.6122598  0.57468563 0.20543718]]
Tanh(Tensorflow): (1, 5)
[[-0.9359674  -0.21431856  0.4274898   0.29222244 -0.8746777 ]]
Tanh(Manual): (1, 5)
[[-0.9359673  -0.21431857  0.42748982  0.29222244 -0.8746777 ]]
ReLU(Tensorflow): (1, 5)
[[0.         0.         0.45682108 0.3009945  0.        ]]
ReLU(Manual): (1, 5)
[[0.         0.         0.45682108 0.3009945  0.        ]]


####Code.1-3-2: Activation in Dense Layer

In [6]:
import tensorflow as tf 
from tensorflow.keras.layers import Dense 
from tensorflow.math import exp

x = tf.random.normal(shape=(1, 5))  # input setting

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh= Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with Sigmoids: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with ReLU: {}\n{}".format(y_relu.shape, y_relu.numpy()))

# forward propagation(manual)
print('=====\n')

W, b = dense_sigmoid.get_weights() 
z = tf.linalg.matmul(x, W) + b 
a = 1 / (1 + exp(-z))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Sigmoid(Manual): {}\n{}".format(a.shape, a.numpy()))

AN with Sigmoids: (1, 1)
[[0.9443495]]
AN with Tanh: (1, 1)
[[-0.9994174]]
AN with ReLU: (1, 1)
[[0.63117677]]
=====

Sigmoid(Tensorflow): (1, 1)
[[0.9443495]]
Sigmoid(Manual): (1, 1)
[[0.9443495]]


###1-4: Artificial Neurons

####Code.1-4-1: Artificial Nuerons

In [8]:
import tensorflow as tf 
from tensorflow.keras.layers import Dense 
from tensorflow.math import exp, maximum 

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform(shape=(1, 10))

dense = Dense(units=1, activation=activation)  

output_tf = dense(x)  # forward propagation
W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B 
if activation == 'sigmoid':
  output_man = 1 / (1 + exp(-y_man)) 
elif activation == 'tanh':
  output_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
  output_man = maximum(y_man, 0)

print("Activation: ", activation)
print("output_tf: {}\n{}\n".format(output_tf.shape, output_tf.numpy()))
print("output_man: {}\n{}\n".format(output_man.shape, output_man.numpy()))

Activation:  sigmoid
output_tf: (1, 1)
[[0.6312545]]

output_man: (1, 1)
[[0.63125443]]



###1-5: Minibatches

####Code.1-5-1: Shapes of Dense Layers

In [9]:
import tensorflow as tf 
from tensorflow.keras.layers import Dense 

N, n_feature = 8, 10   # set input params
x = tf.random.normal(shape=(N, n_feature))  # generate minibatch

dense = Dense(units=1, activation='relu')  # imp. an AN
y = dense(x)  # forward propagation

W, B = dense.get_weights()  # get weight/bias

# print results
print("Shape of x: ", x.shape)
print("Shape of W: ", W.shape)
print("Shape of B: ", B.shape)

Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


####Code.1-5-2: Output Calculations

In [10]:
import tensorflow as tf 
from tensorflow.keras.layers import Dense 

N, n_feature = 8, 10   # set input params
x = tf.random.normal(shape=(N, n_feature))  # generate minibatch

dense = Dense(units=1, activation='sigmoid')  # imp. an AN
y_tf = dense(x)  # forward propagation(Tensorflow)

W, B = dense.get_weights()  # get weight/bias

y_man = tf.linalg.matmul(x, W) + B  # forward propagation(Manual)
y_man = 1 / (1 + tf.math.exp(-y_man)) 

# print resuls
print("Output(Tensorflow): \n", y_tf.numpy())
print("Output(Manuel): \n", y_man.numpy())
# print(tf.math.equal(y_tf, y_man))

Output(Tensorflow): 
 [[0.49694926]
 [0.88359296]
 [0.30778402]
 [0.3294646 ]
 [0.19444221]
 [0.71816885]
 [0.83543885]
 [0.15425962]]
Output(Manuel): 
 [[0.4969492 ]
 [0.88359296]
 [0.307784  ]
 [0.32946455]
 [0.19444221]
 [0.71816885]
 [0.83543885]
 [0.15425964]]
tf.Tensor(
[[False]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]], shape=(8, 1), dtype=bool)
