### 2-1: Dense Layers

####Code.2-1-1: Shapes of Dense Layers


In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

In [4]:
N, n_feature = 1, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print('===== Input/Weight/Bias =====')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

print(W)

===== Input/Weight/Bias =====
X:  (1, 10)
W:  (10, 3)
B:  (3,)
Y:  (1, 3)
[[-0.63633376 -0.6016492   0.65026677]
 [ 0.34131742 -0.5354401  -0.29063672]
 [-0.33520487 -0.5464315   0.5580119 ]
 [ 0.4366324   0.50593483 -0.165559  ]
 [ 0.13914609 -0.21160465 -0.31269494]
 [ 0.6062907   0.3021757  -0.3914429 ]
 [-0.0261265   0.3748448  -0.04034889]
 [ 0.02212119 -0.5095086  -0.4717024 ]
 [ 0.4900279   0.18012542  0.26192462]
 [ 0.3377744  -0.09281927  0.3123567 ]]


In [5]:
N, n_feature = 8, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print('===== Input/Weight/Bias =====')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

===== Input/Weight/Bias =====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


####Code.2-1-2: Output Calculations

In [6]:
import numpy as np
from tensorflow.math import exp 
from tensorflow.linalg import matmul

In [11]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n", Y.numpy())

# calculate with matrix multiplication
z = matmul(X, W) + B
y_man_matmul = 1 / (1 + exp(-z))
print("Y(with matrix multiplication): \n", y_man_matmul.numpy())

# calculate with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
    x = X[x_idx]
    for nu_idx in range(n_neuron):
      w, b = W[:, nu_idx], B[nu_idx]
      z = np.dot(x, w) + b
      # z = tf.reduce_sum(x * w) + b
      a = 1 / (1 + np.exp(-z))
      Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(Tensorflow): 
 [[0.7290487  0.88221335 0.56611776]
 [0.3447923  0.815389   0.65437347]
 [0.69225997 0.79836243 0.8030332 ]
 [0.24527916 0.03019345 0.8761199 ]]
Y(with matrix multiplication): 
 [[0.7290488  0.8822133  0.5661178 ]
 [0.3447923  0.8153889  0.6543735 ]
 [0.69226    0.79836243 0.8030332 ]
 [0.24527916 0.03019341 0.8761199 ]]
Y(with dot products): 
 [[0.72904879 0.88221335 0.56611781]
 [0.34479233 0.81538894 0.65437348]
 [0.69225999 0.79836247 0.80303319]
 [0.24527919 0.03019342 0.87611991]]


###2-2: Cascaded Dense Layers

####Code.2-2-1: Shapes of Cascaded Dense Layers

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [16]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bais
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print('X: {}\n'.format(X.shape))

print('W1: {}'.format(W1.shape))
print('B1: {}'.format(B1.shape))
print('A1: {}\n'.format(A1.shape))

print('W2: {}'.format(W2.shape))
print('B2: {}'.format(B2.shape))
print('Y: {}'.format(Y.shape))


X: (4, 10)

W1: (10, 3)
B1: (3,)
A1: (4, 3)

W2: (3, 5)
B2: (5,)
Y: (4, 5)


####Code.2-2-2: Dense Layers with Python List

In [18]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)

# for dense in dense_layers:
#     print(dense)

for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer", dense_idx+1)
    print(X.shape, '\n')

After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 

After dense layer 5
(4, 50) 



####Code.2-2-3: Output Calculations

In [19]:
from tensorflow.math import exp
from tensorflow.linalg import matmul

In [23]:
N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)  # deep copy

n_neurons = [3, 4, 5]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='sigmoid')
    dense_layers.append(dense)

print("Input: ", X.shape)

# forword propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    w, b = dense.get_weights()

    W.append(w)
    B.append(b)

print("Y(Tensorflow): \n", X.numpy())


# forword propagation(Manuel)
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]

    X_cp = matmul(X_cp, w) + b
    X_cp = 1 / (1 + exp(-X_cp))

print("Y(Manual): \n", X_cp.numpy())

Input:  (4, 10)
Y(Tensorflow): 
 [[0.5604908  0.56944543 0.5075002  0.5595097  0.5870255 ]
 [0.5553303  0.5656578  0.505468   0.5607637  0.59117657]
 [0.58910894 0.595153   0.533249   0.5599146  0.5786364 ]
 [0.5988022  0.5999151  0.5460066  0.55174637 0.55953497]]
Y(Manual): 
 [[0.5604908  0.56944543 0.5075002  0.5595097  0.5870255 ]
 [0.5553303  0.5656578  0.50546795 0.5607637  0.5911766 ]
 [0.58910894 0.59515303 0.533249   0.5599146  0.5786364 ]
 [0.5988022  0.5999151  0.5460066  0.5517464  0.559535  ]]
