###3-4: Softmax Layers

####Code.3-4-1: IO of Softmax

In [1]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

In [5]:
logit = tf.random.uniform(shape=(2, 5), minval=-10, maxval=10)

softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print("Logits: \n", logit.numpy())
print("Probabilities: \n", softmax_value.numpy())
print("Sum of softmax values: \n", softmax_sum)

Logits: 
 [[-2.8187704 -1.166811   4.5657253 -2.7681732  7.2943897]
 [ 9.67091   -9.937418  -5.659673   1.6289692 -8.014133 ]]
Probabilities: 
 [[3.8046590e-05 1.9849637e-04 6.1286025e-02 4.0021168e-05 9.3843746e-01]
 [9.9967825e-01 3.0483978e-09 2.1972141e-07 3.2158056e-04 2.0861403e-08]]
Sum of softmax values: 
 tf.Tensor([1.        1.0000001], shape=(2,), dtype=float32)


####Code.3-4-2: Sotfmax in Dense Layers

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [7]:
logit = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
dense = Dense(units=8, activation='softmax')

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[0.9999999 1.        1.        1.        1.        0.9999999 1.
 1.0000001], shape=(8,), dtype=float32)


###3-5: Multi-class Classifiers

####Code.3-5-1: Multi-class Classifiers

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

In [11]:
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()

        self.dense1 = Dense(units=8, activation='relu')
        self.dense2 = Dense(units=5, activation='relu')
        self.dense3 = Dense(units=3, activation='softmax')


    def call(self, x):
        print("X: {}\n{}\n".format(x.shape, x.numpy()))

        x = self.dense1(x)
        print("A1: {}\n{}\n".format(x.shape, x.numpy()))

        x = self.dense2(x)
        print("A2: {}\n{}\n".format(x.shape, x.numpy()))

        x = self.dense3(x)
        print("A3: {}\n{}\n".format(x.shape, x.numpy()))
        print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
        return x



In [12]:
model = TestModel()

X = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
Y = model(X)

X: (8, 5)
[[-7.90982    -8.037493    7.1193523  -7.0554304   3.4665918 ]
 [-5.0526786  -6.6928267   5.2939367  -5.8131576  -4.986336  ]
 [ 7.492716   -0.32837105 -1.2341309  -5.797119    7.446768  ]
 [-6.3449144   0.05890369 -1.3351707  -1.3934879   9.1919155 ]
 [-2.4816942  -9.675186    2.027502    2.043891    0.7063675 ]
 [ 0.64712715  9.511383    1.315546   -9.982104   -5.6970167 ]
 [-5.064082    4.5740795   6.67889     0.5899143   7.528805  ]
 [-0.81674576  6.281246    0.03149986  0.07367897  2.0998383 ]]

A1: (8, 8)
[[ 0.          0.          3.812935    9.093909   10.769618    5.437073
   3.1220949   0.        ]
 [ 0.          0.          0.          5.8213253  13.31965     1.6708984
   0.25416264  0.        ]
 [ 0.          0.          0.3686568   1.4805602   0.          0.
   5.0539126   0.        ]
 [ 6.0095034   1.1252035   9.775192    1.058625    0.          4.7018704
   4.2241096   0.80030775]
 [ 0.          0.          0.          5.415651    4.157781    0.
   0.          