###4-1: Datasets

####Code.4-1-1: Dataset for Regression

In [1]:
import tensorflow as tf

N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

print(t_weights)
print(t_bias)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)
tf.Tensor([10.], shape=(1,), dtype=float32)


In [2]:
X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y = tf.reduce_sum(t_weights * X, axis=1) + t_bias
print(X.shape, Y.shape)

(8, 5) (8,)


####Code.4-1-2: Dataset for Binary Classification

In [3]:
import tensorflow as tf

N, n_feature = 8, 5
t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y = tf.reduce_sum(t_weights * X, axis=1) + t_bias
Y = tf.cast(Y > 5, tf.int32)


####Code.4-1-3: Dataset for Multi-class Classification

In [7]:
import tensorflow as tf
import matplotlib.pyplot as plt 

plt.style.use('seaborn')

N, n_feature = 30, 2
n_class = 3

X = tf.zeros(shape=(0, n_feature))
Y = tf.zeros(shape=(0, 1), dtype=tf.int32)

# fig, ax = plt.subplots(figsize=(5, 5))
for class_idx in range(n_class):
    center = tf.random.uniform(minval=-15, maxval=15, shape=(2, ))

    x1 = center[0] + tf.random.normal(shape=(N, 1))
    x2 = center[1] + tf.random.normal(shape=(N, 1))

    x = tf.concat((x1, x2), axis=1)
    y = class_idx * tf.ones(shape=(N, 1), dtype=tf.int32)

    X = tf.concat((X, x), axis=0)
    Y = tf.concat((Y, y), axis=0)

####Code.4-1-4: Dataset for Multi-Class Classification with One-hot Encoding

In [9]:
import tensorflow as tf


N, n_feature = 8, 2
n_class = 3

X = tf.zeros(shape=(0, n_feature))
Y = tf.zeros(shape=(0, ), dtype=tf.int32)

for class_idx in range(n_class):
    center = tf.random.uniform(minval=-15, maxval=15, shape=(2, ))

    x1 = center[0] + tf.random.normal(shape=(N, 1))
    x2 = center[1] + tf.random.normal(shape=(N, 1))

    x = tf.concat((x1, x2), axis=1)
    y = class_idx * tf.ones(shape=(N, ), dtype=tf.int32)

    X = tf.concat((X, x), axis=0)
    Y = tf.concat((Y, y), axis=0)

Y = tf.one_hot(Y, depth=n_class, dtype=tf.int32)  # one-hot encoding
print(Y.shape)
print(Y)

(24, 3)
tf.Tensor(
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]], shape=(24, 3), dtype=int32)


####Code.4-1-5: Dataset Objects


In [10]:
import tensorflow as tf 

N, n_feature = 100, 5
batch_size = 32 

t_weights = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
t_bias = tf.constant([10], dtype=tf.float32)

X = tf.random.normal(mean=0, stddev=1, shape=(N, n_feature))
Y = tf.reduce_sum(t_weights * X, axis=1) + t_bias

# create dataset object(from_tensor_slices)
dataset = tf.data.Dataset.from_tensor_slices((X, Y))
dataset = dataset.batch(batch_size).shuffle(100)

for x, y, in dataset:
    print(x.shape, y.shape)

(32, 5) (32,)
(32, 5) (32,)
(4, 5) (4,)
(32, 5) (32,)
